
enum rpmh_regulator_mode {
  RPMH_REGULATOR_MODE_PASS_THROUGH, // only BOB regulators
  RPMH_REGULATOR_MODE_RET,  // Retention mode. Extremely low current.
  RPMH_REGULATOR_MODE_LPM,  // Low power mode
  RPMH_REGULATOR_MODE_AUTO, // Automatically switches between LPM and HPM
  RPMH_REGULATOR_MODE_HPM,  // High power mode
};

enum rpmh_regulator_set {
  RPMH_REGULATOR_SET_ACTIVE = 1,
  RPMH_REGULATOR_SET_SLEEP  = 2,
  RPMH_REGULATOR_SET_ALL    = 3,
};

enum rpmh_regulator_type {
  RPMH_REGULATOR_TYPE_PMIC4_LDO = 1,
  RPMH_REGULATOR_TYPE_PMIC4_HFSMPS,
  RPMH_REGULATOR_TYPE_PMIC4_FTSMPS,
  RPMH_REGULATOR_TYPE_PMIC4_BOB,
  RPMH_REGULATOR_TYPE_PMIC5_LDO,
  RPMH_REGULATOR_TYPE_PMIC5_HFSMPS,
  RPMH_REGULATOR_TYPE_PMIC5_FTSMPS,
  RPMH_REGULATOR_TYPE_PMIC5_BOB,
};
